# Generated by Django 4.0.5 on 2022-06-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_reporter_delete_einsatz_delete_taucher_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
